# -*- coding: utf-8 -*-
#
# This file is part of hepcrawl.
# Copyright (C) 2015, 2016 CERN.
#
# hepcrawl is a free software; you can redistribute it and/or modify it
# under the terms of the Revised BSD License; see LICENSE file for
# more details.

sudo: false

language: python

cache:
  - pip

python:
  - "2.7"

env:
  - EXTRAS=docs,tests

before_install:
  - "travis_retry pip install --upgrade pip setuptools py"
  - "travis_retry pip install twine wheel coveralls check-manifest"

install:
  - "travis_retry pip install -e .[${EXTRAS}]"

script:
  - sphinx-build -qnNW docs docs/_build/html
  - check-manifest --ignore "*.pyc"
  - python setup.py test

after_success:
  - coveralls

notifications:
  email: false
